<template>
  <div>
    <!--保活模式，name相同则复用一个子应用实例，改变url无效，必须采用通信的方式告知路由变化 -->
    <WujieVue
      width="100%"
      height="100%"
      name="react-in-all"
      url="http://127.0.0.1:8002/"
      :sync="true"
    ></WujieVue>
    <WujieVue
      width="100%"
      height="100%"
      name="vue3-in-all"
      url="http://127.0.0.1:8001/"
      sync="true"
    ></WujieVue>
  </div>
</template>
