version: '3.0'

services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 8080:80
    volumes:
      - E:/Documents/GitHub/io/demo/micro-front/wujie-micro-demo/www/nginx-1.22.1/html/:/usr/share/nginx/html
      - E:/Documents/GitHub/io/demo/micro-front/wujie-micro-demo/www/nginx-1.22.1/logs/:/var/log/nginx/
      - E:/Documents/GitHub/io/demo/micro-front/wujie-micro-demo/www/nginx-1.22.1/nginx.conf:/etc/nginx/nginx.conf